

function preloader() {
    const imagesList = [
           "./images/solar.jpg",
           "./images/geothermal.jpg",
           "./images/hydroelec.jpg"
        ];
    const images = [];
    for (let i = 0; i < imagesList.length; i++) {
        images[i] = new Image();
        images[i].src = imagesList[i];
    }

    console.log(`Preloaded images:\n\t${images[0].src}\n\t${images[1].src}\n\t${images[2].src}`);
};

window.addEventListener("load", preloader);


let buttonNum = document.querySelectorAll("button");                      


let commodity = {
    Solar: {
        headingContent: "SOLAR ENERGY",
        bodyText: "The most direct use of this renewable energy source, is achieved by capturing the sun’s energy directly. A variety of solar energy technologies are used to convert the sun’s energy and light into heat, illumination, hot water, electricity and (paradoxically) cooling systems for businesses and industry. Solar hot water systems can be used to heat buildings by circulating water through flat-plate solar collectors. The sun’s heat can be concentrated by mirror-covered dishes that are focused to boil water in a conventional steam generator to produce electricity. ",
        imgUrl: "./images/solar.jpg",
        imgAlt: "Solar"
    },

    Geothermal: {
        headingContent: "GEOTHERMAL ENERGY",
        bodyText: "Geothermal energy, as the name implies, is derived from the heat of the earth itself. This heat can be sourced close to the surface or from heated rock and reservoirs of hot water miles beneath our feet. Geothermal power plants harness these heat sources to generate electricity. On a much smaller scale, a geothermal heat pump system can leverage the constant temperature of the ground just ten feet under the surface to help supply heat to a nearby building in the winter, or help cool it in the summer.",
        imgUrl: "./images/geothermal.jpg",
        imgAlt: "Factory"
    },

    Hydroelectric: {
        headingContent: "HYDROELECTRIC ENERGY",
        bodyText: "The most familiar type of hydroelectric power is generated by a system in which dams are constructed to store water in a reservoir. When released, the water flows through turbines to produce electricity. This is known as “pumped-storage hydropower”—water is cycled between lower and upper reservoirs to control electricity generation between times of low and peak demand. Another type, called “run-of-river hydropower,” funnels a portion of river flow through a channel and does not require a dam. Hydropower plants can range in size from massive projects like the Hoover Dam to micro-hydroelectric power systems.",
        imgUrl: "./images/hydroelec.jpg",
        imgAlt: "Dam"
    }
};


let data = document.getElementById("maincontent");


buttonList[0].setAttribute("id", "active-button");


data.innerHTML = `<h1>${object.Solar.headingContent}</h1>
     <img src="${object.Solar.imgUrl}" alt="${object.Solar.imgAlt}">
     <p>${object.Solar.bodyText}</p>`;

function handleSelection() {

    for (let i = 0; i < buttonList.length; i++) {
        if (buttonList[i].hasAttribute("id")) {
            buttonList[i].removeAttribute("id");
        }
    }

    this.setAttribute("id", "active-button");

    for (let i = 0; i < buttonList.length; i++) {
        if (buttonList[i].hasAttribute("id")) {
            if (i == 0) {
                data.innerHTML = `<h1>${commodity.Solar.headingContent}</h1><img src="${commodity.Solar.imgUrl}" alt="${commodity.Solar.imgAlt}"><p>${commodity.Solar.bodyText}</p>`;
            }
            if (i == 1) {
                data.innerHTML = `<h1>${commodity.Geothermal.headingContent}</h1><img src="${commodity.Geothermal.imgUrl}" alt="${commodity.Geothermal.imgAlt}"><p>${commodity.Geothermal.bodyText}</p>`;
            }
            if (i == 2) {
                data.innerHTML = `<h1>${commodity.Hydroelectric.headingContent}</h1><img src="${commodity.Hydroelectric.imgUrl}" alt="${commodity.Hydroelectric.imgAlt}"><p>${commodity.Hydroelectric.bodyText}</p>`;
            }
        }
    }

} 

for (let i = 0; i < buttonList.length; i++) {
    buttonList[i].addEventListener("click", handleSelection)
}
